name: Delete stale quay PR image tags
on:
  pull_request:

jobs:
  delete-pr-quay-image:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Install skopeo
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install skopeo
      - name: Login to quay.io
        run: |
          skopeo login quay.io -u ${{ secrets.QUAY_ROBOT_USERNAME }} -p ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Delete PR images
        run: |
          for tag in "pr-69" "pr-101" "pr-103" "pr-112" "pr-107" "pr-123" "pr-119" "pr-114" "pr-118" "pr-124" "pr-126" "pr-131" "pr-135" "pr-140" "pr-141" "pr-142" "pr-143" "pr-144" "pr-148" "pr-149" "pr-150" "pr-151" "pr-153" "pr-152" "pr-168" "pr-171"; do
            skopeo delete docker://quay.io/opendatahub/caikit-tgis-serving:${tag}
          done
