name: Delete quay image on PR closed
on:
  pull_request_target:
    types: [closed]
    branches:
      - "main"
    paths-ignore:
      - "LICENSE"
      - "**/.gitignore"
      - "**.md"
      - "**.adoc"
      - "*.txt"
      - "Makefile"
      - ".github/**"
      - "docs/**"
      - "demo/**"

jobs:
  delete-pr-quay-image:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Install skopeo
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install skopeo
      - name: Login to quay.io
        run: |
          skopeo login quay.io -u ${{ secrets.QUAY_ROBOT_USERNAME }} -p ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Delete PR image
        env:
          PR: ${{ github.event.pull_request.number }}
        run: |
          skopeo delete docker://quay.io/opendatahub/caikit-tgis-serving:pr-${PR}
